baseURL = "https://www.micromdm.io/"
languageCode = "en-us"
title = "MicroMDM Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	author = "Joe Blau"
	description = "MicroMDM documentation."
	copyright = "Released under the MIT license"
	provider = "GitHub"
	repo_url = "https://github.com/micromdm/docs"
	logo = "images/logo.svg"
	favicon = "images/favicon.ico"

[params.palette]
	primary = "light-blue"
	accent  = "red"

[params.font]
	text = "Ubuntu"
	code = "Ubuntu Mono"

[[menu.main]]
	name   = "Overview"
	url    = ""
	weight = 10

[[menu.main]]
	name   = "Getting Started"
	url    = "getting-started"
	weight = 20

[[menu.main]]
	name   = "MicroMDM"
	url    = "micromdm"
	weight = 30

[[menu.main]]
	name   = "API"
	url    = "api"
	weight = 40

[[menu.main]]
	name   = "Troubleshooting"
	url    = "troubleshooting"
	weight = 50

[[menu.main]]
	name   = "Utilities"
	url    = "utilities"
	weight = 60

[[menu.main]]
	name   = "Community"
	url    = "community"
	weight = 70

[[menu.main]]
	name   = "RFCs"
	url    = "rfcs"
	weight = 80

[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true